#!/bin/sh

. $HOME/.keenetic
NAME=$(basename $0)

echo "[*] $NAME: Makefiles upload started at: "`date`

rsync -av --delete-after --log-file=$DIR_LOG/makefiles-$DATE.log $DIR_MAKEFILES/ $RSYNC_DST/makefiles/

keenetic-rsync-logs
