#!/bin/sh

. $HOME/.keenetic
NAME=$(basename $0)

keenetic-makefiles-backup && keenetic-rsync-makefiles

echo "\n[*] $NAME: Compilation started at: "`date`"\n"
mkdir -p $DIR_LOG
cd $DIR_KEENETIC
make V=99 > $DIR_LOG/build-$DATE.log 2>&1 && keenetic-rsync-logs && keenetic-rsync-packages

echo "[*] $NAME: All done at: "`date`"\n"
